language: php

php:
  - 5.6
  - 7.0
  - 7.1
  - hhvm

addons:
  apt:
    packages:
      - openjdk-7-jdk

before_install:
  - curl -sL https://deb.nodesource.com/setup_6.x | sudo -E bash -
  - sudo apt-get install --yes nodejs
  - npm install -g grunt-cli

install:
  - npm install
  - composer install

script:
  - grunt

after_script:
  - php vendor/bin/coveralls -v
  - chmod +x code-climate-test-reporter
  - CODECLIMATE_REPO_TOKEN=iuxZEsKGmIXjOGObP1WiZ1VmOFybvyUs5 ./code-climate-test-reporter
